### PR TITLE
Add Aqua and fix arising issues

### PR DESCRIPTION
**Pull request by jonschumacher**

### CODE REVIEW

**Comment by jonschumacher** [comment]
@tknopp To make this work I had to remove the re-export for ImageMetadata since it exports `data` which results in an undefined export. Is this fine for you?

**Comment by tknopp** [comment]
yes, I removed reexport altogether since it hides dependencies. Important is to do a correct version bump before releasing since it will break depending packages. I have already bumped the version on master.

**Comment by tknopp** [comment]
I am not sure, why the documentation building gives a failure. Maybe that is aqua related.

**Comment by jonschumacher** [comment]
It is due to a major release of Documenter: https://github.com/JuliaDocs/Documenter.jl/blob/v1.0.0/CHANGELOG.md#breaking
I will fix it prior to the release.

**Pull request merged**
