### PR TITLE
Add support for field measurements

### LINKED ISSUE #36: Add support for field measurements
During our discussions on https://github.com/MagneticParticleImaging/MPIMeasurements.jl/pull/27, @jusack and me came across the [definition of the field measurement format](https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/1d856c1c3db92b95ecc3b255c6a2890e1e91d4b6/src/Measurements/MagneticFieldSweepCurrents.jl#L72). Should this be moved over to MPIFiles or stay in MPIMeasurements? Do you see cases where there should be more information stored in the file than what is currently being done? I guess `timestamp`, `currents` and `fieldsError` could be optional.

### PR DESCRIPTION
**Pull request by jonschumacher**
Closes #36.

### CODE REVIEW

**Comment by tknopp** [comment]
Is this more or less what we had in MPIMeasurements moved to MPIFiles?

**Comment by jonschumacher** [comment]
Mostly yes, plus a struct in between. I left out `unitCoords` and `unitFields` in favor of always going for the base unit. I added the fields `sensorOffset`, `temperature`, `fieldsFrequency` and `description` to allow for some more metadata especially with the Lakeshore F71.

**Comment by tknopp** [comment]
Ok, I am right now not 100% sure in what order we are going to merge this since potentially this will break MPIMeasurement master.

**Comment by jonschumacher** [comment]
I guess the easiest way would be to just wait until I have the changes in MPIMeasurements ready to merge including the tests. I will now add the code for making robot-based magnetic field measurements in MPIMeasurements and write appropriate in-silico tests based on the changes in this PR's branch.

**Comment by jonschumacher** [comment]
Will be merged with #42, and thus this PR can be closed.

**Pull request closed without merging**
